language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy3"
sudo: false
dist: trusty
script:
  # Unit tests
  - python run_unit_tests.py
  # Integration tests
  - python run_integration_tests.py
  # Sanity check that command line syntax works
  - python splbytecode.py examples/hello.spl --cls-name Hello
  - java Hello
