language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy3"
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - oracle-java9-set-default
script:
  - python run_all_tests.py
  - python compiler.py examples/hello.spl --cls-name Hello 
  - java Hello
  - python compiler.py examples/goto.spl --cls-name Goto 
  - java Goto
  - python compiler.py examples/incrementor.spl --cls-name Incrementor 
  - java Incrementor 100
  - python compiler.py examples/condgoto.spl --cls-name Condgoto 
  - java Condgoto 15
